language: node_js
node_js:
  - "lts/*"
script:
  - echo "Deploying"
  - npm run build
install:
  - npm install
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
branches:
  only:
  - production
cache:
  directories:
    - "node_modules"
env:
  - NODE_ENV=development